name: Build And Deploy Actions

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: package install
        run: |
          cd ai-front
          npm install

      - name: package install
        run: |
          cd ai-front
          npm run build

      - name: docker image build
        run: docker build --platform amd64 -t ${{secrets.DOCKER_HUB_REPO}} .

      - name: docker hub push
        run: |
          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
          docker push ${{secrets.DOCKER_HUB_REPO}}

  deploy:
    name: Deploy Job
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
